import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {onAuthStateChanged,signInWithPopup,signOut,type User} from 'firebase/auth';
import {collection,doc,getDoc,onSnapshot,serverTimestamp,setDoc,Timestamp,updateDoc,query,where,type DocumentData} from 'firebase/firestore';
import {auth,provider,db,configured} from './firebase';
import Workspace from './LegacyWorkspace';
import './globals.css';
const durations=[['5 hours',5],['10 hours',10],['24 hours',24],['48 hours',48],['Unlimited',0]] as const;
export default function LegacyApp(){
 const [user,setUser]=useState<User|null>(null),[loading,setLoading]=useState(true),[owner,setOwner]=useState(false),[configuredOwner,setConfiguredOwner]=useState(false),[grant,setGrant]=useState<DocumentData|null>(null),[request,setRequest]=useState<DocumentData|null>(null),[requests,setRequests]=useState<DocumentData[]>([]),[grants,setGrants]=useState<DocumentData[]>([]),[message,setMessage]=useState(''),[now,setNow]=useState(Date.now());
 useEffect(()=>onAuthStateChanged(auth,u=>{setUser(u);setLoading(false)}),[]);
 useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),30000);return()=>clearInterval(timer)},[]);
 useEffect(()=>{if(!user)return;let live=true;getDoc(doc(db,'config','owner')).then(s=>{if(live){setConfiguredOwner(s.exists());setOwner(s.data()?.uid===user.uid)}}).catch(e=>setMessage(e.message));const offGrant=onSnapshot(doc(db,'grants',user.uid),s=>setGrant(s.data()||null),e=>setMessage(e.message));const offRequest=onSnapshot(doc(db,'requests',user.uid),s=>setRequest(s.data()||null),e=>setMessage(e.message));return()=>{live=false;offGrant();offRequest();setOwner(false);setGrant(null);setRequest(null)}},[user]);
 useEffect(()=>{if(!owner)return;const off=onSnapshot(query(collection(db,'requests'),where('status','==','pending')),s=>setRequests(s.docs.map(d=>d.data())),e=>setMessage(e.message));const offGrants=onSnapshot(collection(db,'grants'),snapshot=>setGrants(snapshot.docs.map(d=>({uid:d.id,...d.data()}))),e=>setMessage(e.message));return()=>{off();offGrants()}},[owner]);
 const approved=Boolean(owner||grant?.active===true&&(grant?.permanent===true||grant?.expiresAt?.toMillis?.()>now));
 const requestAccess=async()=>{if(!user)return;try{await setDoc(doc(db,'requests',user.uid),{uid:user.uid,email:user.email||'',name:user.displayName||'',status:'pending',requestedAt:serverTimestamp()});setMessage('Access request sent.')}catch(e){setMessage(String(e))}};
 const decide=async(uid:string,hours:number)=>{try{await setDoc(doc(db,'grants',uid),{active:true,permanent:hours===0,expiresAt:hours?Timestamp.fromMillis(Date.now()+hours*3600000):null,updatedAt:serverTimestamp()});await updateDoc(doc(db,'requests',uid),{status:'approved'});setMessage('Access granted.')}catch(e){setMessage(String(e))}};
 const revoke=async(uid:string)=>{try{await updateDoc(doc(db,'grants',uid),{active:false,updatedAt:serverTimestamp()});setMessage('Access revoked.')}catch(e){setMessage(String(e))}};
 const reject=async(uid:string)=>{try{await updateDoc(doc(db,'requests',uid),{status:'rejected'});setMessage('Request rejected.')}catch(e){setMessage(String(e))}};
 if(!configured)return <div className="gate"><h1>WorkspaceDashboard</h1><p>Firebase configuration is missing. Add the VITE_FIREBASE_* values before publishing.</p></div>;
 if(loading)return <div className="gate">Loading workspace…</div>;
 if(!user)return <div className="gate"><div className="gate-card"><img className="gate-logo" src={import.meta.env.BASE_URL+"workspace-dashboard-icon.png"} alt=""/><h1>WorkspaceDashboard</h1><p>Sign in with Google to access this private workspace.</p><button className="gate-primary" onClick={()=>signInWithPopup(auth,provider).catch(e=>setMessage(e.message))}>Continue with Google</button>{message&&<p role="alert">{message}</p>}</div></div>;
 if(!configuredOwner)return <div className="gate"><div className="gate-card"><h1>Owner setup</h1><p>Signed in as {user.email}. Create <code>config/owner</code> in Firestore with a string field <code>uid</code> set to:</p><code className="gate-uid">{user.uid}</code><p>Refresh after saving. Only the Firebase console can set the owner.</p><button onClick={()=>signOut(auth)}>Sign out</button>{message&&<p role="alert">{message}</p>}</div></div>;
 if(!approved)return <div className="gate"><div className="gate-card"><h1>Access to WorkspaceDashboard</h1><p>Signed in as {user.email}</p><p>{request?.status==='pending'?'Your request is waiting for the owner.':grant?.active?'Your access has expired. Request a new grant.':request?.status==='rejected'?'Your previous request was declined.':'Ask the owner for time limited access.'}</p>{request?.status!=='pending'&&<button className="gate-primary" onClick={requestAccess}>Request access</button>}<button onClick={()=>signOut(auth)}>Sign out</button>{message&&<p role="alert">{message}</p>}</div></div>;
 return <div className="site-wrap"><div className="account-strip"><span>{owner?'Owner':'Viewer'} · {user.email}</span>{owner&&<button onClick={()=>document.getElementById('access-panel')?.scrollIntoView({behavior:'smooth'})}>Access requests {requests.length?`(${requests.length})`:''}</button>}<button onClick={()=>signOut(auth)}>Sign out</button></div><Workspace readOnly={!owner}/>{owner&&<section className="access-panel" id="access-panel"><h2>Access requests</h2><p>Approved visitors can view records until their grant expires. Only you can edit them.</p>{requests.length?requests.map(r=><div className="request-row" key={r.uid}><span><strong>{r.name||r.email}</strong><small>{r.email}</small></span><div>{durations.map(([label,hours])=><button key={label} onClick={()=>decide(r.uid,hours)}>{label}</button>)}<button className="danger" onClick={()=>reject(r.uid)}>Reject</button></div></div>):<p>No pending requests.</p>}<h3>Active grants</h3>{grants.filter(g=>g.active&&(g.permanent||g.expiresAt?.toMillis?.()>now)).map(g=><div className="request-row" key={g.uid}><span><strong>{requests.find(r=>r.uid===g.uid)?.email||g.uid}</strong><small>{g.permanent?'Unlimited':`Until ${g.expiresAt?.toDate?.().toLocaleString()}`}</small></span><button className="danger" onClick={()=>revoke(g.uid)}>Revoke</button></div>)}</section>}{message&&<div className="toast" role="status" onClick={()=>setMessage('')}>{message} ×</div>}</div>;
}

