import React,{useEffect,useState} from 'react';
import {onAuthStateChanged,signInWithPopup,signOut,type User} from 'firebase/auth';
import {collection,doc,getDoc,onSnapshot,query,serverTimestamp,setDoc,Timestamp,updateDoc,where,type DocumentData} from 'firebase/firestore';
import {auth,provider,db,configured} from './firebase';
import Workspace from './Workspace';
import {migrateLegacyOwnerRecords} from './store';
import './globals.css';
const durations=[['5 hours',5],['10 hours',10],['24 hours',24],['48 hours',48],['Unlimited',0]] as const;
const active=(item:DocumentData|null,now:number)=>Boolean(item?.active===true&&(item.permanent===true||item.expiresAt?.toMillis?.()>now));
export default function SecureApp(){
 const [user,setUser]=useState<User|null>(null),[loading,setLoading]=useState(true),[ownerUid,setOwnerUid]=useState<string|null>(null),[ownerReady,setOwnerReady]=useState(false),[grant,setGrant]=useState<DocumentData|null>(null),[invite,setInvite]=useState<DocumentData|null>(null),[request,setRequest]=useState<DocumentData|null>(null),[requests,setRequests]=useState<DocumentData[]>([]),[grants,setGrants]=useState<DocumentData[]>([]),[invites,setInvites]=useState<DocumentData[]>([]),[message,setMessage]=useState(''),[now,setNow]=useState(Date.now()),[selected,setSelected]=useState<'mine'|'shared'>('mine'),[migration,setMigration]=useState<'pending'|'running'|'done'|'error'>('pending'),[shareEmail,setShareEmail]=useState(''),[shareHours,setShareHours]=useState(24);
 useEffect(()=>onAuthStateChanged(auth,u=>{setUser(u);setLoading(false);setSelected('mine');setMigration('pending')}),[]);
 useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),15000);return()=>clearInterval(timer)},[]);
 useEffect(()=>{if(!user)return;let live=true;setOwnerReady(false);getDoc(doc(db,'config','owner')).then(s=>{if(live){setOwnerUid(s.data()?.uid||null);setOwnerReady(true)}}).catch(e=>{if(live){setOwnerUid(null);setOwnerReady(true);setMessage(`Owner lookup failed: ${e.message}`)}});const offGrant=onSnapshot(doc(db,'grants',user.uid),s=>setGrant(s.data()||null),e=>setMessage(e.message));const offRequest=onSnapshot(doc(db,'requests',user.uid),s=>setRequest(s.data()||null),e=>setMessage(e.message));const email=user.email?.toLowerCase();const offInvite=email?onSnapshot(doc(db,'invites',email),s=>setInvite(s.data()||null),e=>setMessage(e.message)):()=>{};return()=>{live=false;offGrant();offRequest();offInvite();setOwnerUid(null);setOwnerReady(false);setGrant(null);setRequest(null);setInvite(null)}},[user]);
 const owner=Boolean(user&&ownerUid===user.uid);
 useEffect(()=>{if(!owner)return;const off=onSnapshot(query(collection(db,'requests'),where('status','==','pending')),s=>setRequests(s.docs.map(d=>d.data())),e=>setMessage(e.message));const offGrants=onSnapshot(collection(db,'grants'),s=>setGrants(s.docs.map(d=>({uid:d.id,...d.data()}))),e=>setMessage(e.message));const offInvites=onSnapshot(collection(db,'invites'),s=>setInvites(s.docs.map(d=>({email:d.id,...d.data()}))),e=>setMessage(e.message));return()=>{off();offGrants();offInvites()}},[owner]);
 const sharedAvailable=Boolean(!owner&&ownerUid&&(active(grant,now)||active(invite,now)));
 useEffect(()=>{if(selected==='shared'&&!sharedAvailable)setSelected('mine')},[selected,sharedAvailable]);
 useEffect(()=>{if(!owner||!user||migration!=='pending')return;setMigration('running');migrateLegacyOwnerRecords(user.uid).then(count=>{setMigration('done');if(count)setMessage(`Moved ${count} existing records into your private workspace.`)}).catch(e=>{setMigration('error');setMessage(`Migration failed: ${e.message}`)})},[owner,user,migration]);
 const requestAccess=async()=>{if(!user)return;try{await setDoc(doc(db,'requests',user.uid),{uid:user.uid,email:user.email||'',name:user.displayName||'',status:'pending',requestedAt:serverTimestamp()});setMessage('Access request sent to the owner.')}catch(e){setMessage(String(e))}};
 const decide=async(uid:string,hours:number)=>{try{await setDoc(doc(db,'grants',uid),{active:true,permanent:hours===0,expiresAt:hours?Timestamp.fromMillis(Date.now()+hours*3600000):null,updatedAt:serverTimestamp()});await updateDoc(doc(db,'requests',uid),{status:'approved'});setMessage('Access granted.')}catch(e){setMessage(String(e))}};
 const revoke=async(uid:string)=>{try{await updateDoc(doc(db,'grants',uid),{active:false,updatedAt:serverTimestamp()});setMessage('Access revoked.')}catch(e){setMessage(String(e))}};
 const reject=async(uid:string)=>{try{await updateDoc(doc(db,'requests',uid),{status:'rejected'});setMessage('Request rejected.')}catch(e){setMessage(String(e))}};
 const share=async()=>{const email=shareEmail.trim().toLowerCase();if(!/^[^\s@/]+@[^\s@/]+\.[^\s@/]+$/.test(email)){setMessage('Enter a valid Google account email.');return}if(email===user?.email?.toLowerCase()){setMessage('This is your own account.');return}try{await setDoc(doc(db,'invites',email),{email,active:true,permanent:shareHours===0,expiresAt:shareHours?Timestamp.fromMillis(Date.now()+shareHours*3600000):null,updatedAt:serverTimestamp()});setShareEmail('');setMessage(`Shared your dashboard with ${email}.`)}catch(e){setMessage(String(e))}};
 const revokeInvite=async(email:string)=>{try{await updateDoc(doc(db,'invites',email),{active:false,updatedAt:serverTimestamp()});setMessage(`Revoked email access for ${email}.`)}catch(e){setMessage(String(e))}};
 if(!configured)return <div className="gate"><h1>WorkspaceDashboard</h1><p>Firebase configuration is missing.</p></div>;
 if(loading)return <div className="gate">Loading workspace…</div>;
 if(!user)return <div className="gate"><div className="gate-card"><img className="gate-logo" src={import.meta.env.BASE_URL+'workspace-dashboard-icon.png'} alt=""/><h1>WorkspaceDashboard</h1><p>Sign in with Google to open your private dashboard.</p><button className="gate-primary" onClick={()=>signInWithPopup(auth,provider).catch(e=>setMessage(e.message))}>Continue with Google</button>{message&&<p role="alert">{message}</p>}</div></div>;
 if(!ownerReady)return <div className="gate">Checking workspace access…</div>;
 const viewingShared=selected==='shared'&&sharedAvailable;
 return <div className="site-wrap"><div className="account-strip"><strong>Workspace</strong><button className={!viewingShared?'workspace-choice selected':''} onClick={()=>setSelected('mine')}>My dashboard</button>{sharedAvailable&&<button className={viewingShared?'workspace-choice selected':''} onClick={()=>setSelected('shared')}>Shared dashboard</button>}<span>{viewingShared?'View only · ':''}{user.email}</span>{owner&&<button onClick={()=>document.getElementById('access-panel')?.scrollIntoView({behavior:'smooth'})}>Sharing {requests.length?`(${requests.length} requests)`:''}</button>}<button onClick={()=>signOut(auth)}>Sign out</button></div>
 {owner&&migration!=='done'?<div className="gate"><div className="gate-card"><h2>{migration==='error'?'Workspace migration needs attention':'Securing your existing records…'}</h2><p>{migration==='error'?'Your existing data remains in place. Retry after checking the Firestore rules.':'Moving existing records to your private dashboard. Please keep this page open.'}</p>{migration==='error'&&<button className="gate-primary" onClick={()=>setMigration('pending')}>Retry migration</button>}{message&&<p role="alert">{message}</p>}</div></div>:<Workspace key={viewingShared?ownerUid!:user.uid} workspaceUid={viewingShared?ownerUid!:user.uid} readOnly={viewingShared}/>}
 {!owner&&ownerUid&&!sharedAvailable&&<section className="access-panel"><h2>Shared dashboard</h2><p>Your dashboard is private. To view the owner's dashboard, request access. The owner can grant or revoke it at any time.</p><button onClick={requestAccess} disabled={request?.status==='pending'}>{request?.status==='pending'?'Request pending':'Request access'}</button></section>}
 {owner&&<section className="access-panel" id="access-panel"><h2>Share your dashboard</h2><p>Only your Google account can edit this dashboard. People you approve can view it for the chosen duration. Everyone keeps a separate private dashboard.</p><div className="share-form"><input aria-label="Google account email" type="email" placeholder="person@gmail.com" value={shareEmail} onChange={e=>setShareEmail(e.target.value)}/><select aria-label="Access duration" value={shareHours} onChange={e=>setShareHours(Number(e.target.value))}>{durations.map(([label,hours])=><option key={label} value={hours}>{label}</option>)}</select><button onClick={share}>Share by email</button></div><h3>Access requests</h3>{requests.length?requests.map(r=><div className="request-row" key={r.uid}><span><strong>{r.name||r.email}</strong><small>{r.email}</small></span><div>{durations.map(([label,hours])=><button key={label} onClick={()=>decide(r.uid,hours)}>{label}</button>)}<button className="danger" onClick={()=>reject(r.uid)}>Reject</button></div></div>):<p>No pending requests.</p>}<h3>Active access</h3>{grants.filter(g=>active(g,now)).map(g=><div className="request-row" key={g.uid}><span><strong>{requests.find(r=>r.uid===g.uid)?.email||g.uid}</strong><small>Approved account · {g.permanent?'Unlimited':`Until ${g.expiresAt?.toDate?.().toLocaleString()}`}</small></span><button className="danger" onClick={()=>revoke(g.uid)}>Revoke</button></div>)}{invites.filter(i=>active(i,now)).map(i=><div className="request-row" key={i.email}><span><strong>{i.email}</strong><small>Shared by email · {i.permanent?'Unlimited':`Until ${i.expiresAt?.toDate?.().toLocaleString()}`}</small></span><button className="danger" onClick={()=>revokeInvite(i.email)}>Revoke</button></div>)}{!grants.some(g=>active(g,now))&&!invites.some(i=>active(i,now))&&<p>No active shares.</p>}<p className="muted">If the same person has both an account approval and an email share, revoke both to remove all access. Revocation prevents future reads; previously saved copies cannot be recalled.</p></section>}
 {message&&<div className="toast" role="status" onClick={()=>setMessage('')}>{message} ×</div>}</div>;
}
